name: ent_tutorial

channels:
    - defaults
    - conda-forge

dependencies:
    - python>=3.8  # The first line should always be python version
    - pip
    - pillow
    - flask  # chapter 3
    - kafka-python  # chapter 4
    - pyodbc  # chapter 6
    - pandas  # chapter 7
    - pip:
          - flask-session
          - pipdeptree # or conda install -c conda-forge pipdeptree
          - wordcloud # extra libs
          - pypdf2 # extra libs
          - jieba # extra libs, Chinese
          - paddlepaddle  # OCR Chinese
          - paddleocr

# --use-feature=2020-resolver
