name: ent_tutorial

channels:
    - defaults
    - conda-forge

dependencies:
    - python>=3.8  # The first line should always be python version
    - pip
    - pillow
    - flask  # chapter 3
    - kafka-python  # chapter 4
    - pip:
          - flask-session
          - pipdeptree # or conda install -c conda-forge pipdeptree
